# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: tinkoff_stt.proto for package 'tinkoff.cloud.stt.v1'

require 'grpc'
require_relative 'tinkoff_stt_pb'

module Tinkoff
  module Cloud
    module Stt
      module V1
        module SpeechToText
          class Service

            include GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'tinkoff.cloud.stt.v1.SpeechToText'

            rpc :Recognize, ::Tinkoff::Cloud::Stt::V1::RecognizeRequest, ::Tinkoff::Cloud::Stt::V1::RecognizeResponse
            # Method to recognize whole audio at once: sending complete audio, getting complete recognition result.
            rpc :StreamingRecognize, stream(::Tinkoff::Cloud::Stt::V1::StreamingRecognizeRequest), stream(::Tinkoff::Cloud::Stt::V1::StreamingRecognizeResponse)
            # Method for streaming recognition.
          end

          Stub = Service.rpc_stub_class
        end
        # Speech recognition.
      end
    end
  end
end
