# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from tinkoff.cloud.tts.v1 import tts_pb2 as tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2


class TextToSpeechStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListVoices = channel.unary_unary(
        '/tinkoff.cloud.tts.v1.TextToSpeech/ListVoices',
        request_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.ListVoicesRequest.SerializeToString,
        response_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.ListVoicesResponses.FromString,
        )
    self.Synthesize = channel.unary_unary(
        '/tinkoff.cloud.tts.v1.TextToSpeech/Synthesize',
        request_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechRequest.SerializeToString,
        response_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechResponse.FromString,
        )
    self.StreamingSynthesize = channel.unary_stream(
        '/tinkoff.cloud.tts.v1.TextToSpeech/StreamingSynthesize',
        request_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechRequest.SerializeToString,
        response_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.StreamingSynthesizeSpeechResponse.FromString,
        )


class TextToSpeechServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListVoices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Synthesize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamingSynthesize(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TextToSpeechServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListVoices': grpc.unary_unary_rpc_method_handler(
          servicer.ListVoices,
          request_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.ListVoicesRequest.FromString,
          response_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.ListVoicesResponses.SerializeToString,
      ),
      'Synthesize': grpc.unary_unary_rpc_method_handler(
          servicer.Synthesize,
          request_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechRequest.FromString,
          response_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechResponse.SerializeToString,
      ),
      'StreamingSynthesize': grpc.unary_stream_rpc_method_handler(
          servicer.StreamingSynthesize,
          request_deserializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.SynthesizeSpeechRequest.FromString,
          response_serializer=tinkoff_dot_cloud_dot_tts_dot_v1_dot_tts__pb2.StreamingSynthesizeSpeechResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tinkoff.cloud.tts.v1.TextToSpeech', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
