# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

use_frameworks!

target 'voicekit-demo' do
  # Pods for voicekit-demo
  pod 'VoiceKit', :path => '.'
  pod 'SwiftJWT'
  pod 'CSIOpusCodec', :path => '.'
end
