// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tinkoff/cloud/tts/v1/tts.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Tinkoff.Cloud.Tts.V1 {
  public static partial class TextToSpeech
  {
    static readonly string __ServiceName = "tinkoff.cloud.tts.v1.TextToSpeech";

    static readonly grpc::Marshaller<global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest> __Marshaller_tinkoff_cloud_tts_v1_ListVoicesRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses> __Marshaller_tinkoff_cloud_tts_v1_ListVoicesResponses = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest> __Marshaller_tinkoff_cloud_tts_v1_SynthesizeSpeechRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse> __Marshaller_tinkoff_cloud_tts_v1_SynthesizeSpeechResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse> __Marshaller_tinkoff_cloud_tts_v1_StreamingSynthesizeSpeechResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest, global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses> __Method_ListVoices = new grpc::Method<global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest, global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListVoices",
        __Marshaller_tinkoff_cloud_tts_v1_ListVoicesRequest,
        __Marshaller_tinkoff_cloud_tts_v1_ListVoicesResponses);

    static readonly grpc::Method<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse> __Method_Synthesize = new grpc::Method<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Synthesize",
        __Marshaller_tinkoff_cloud_tts_v1_SynthesizeSpeechRequest,
        __Marshaller_tinkoff_cloud_tts_v1_SynthesizeSpeechResponse);

    static readonly grpc::Method<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse> __Method_StreamingSynthesize = new grpc::Method<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamingSynthesize",
        __Marshaller_tinkoff_cloud_tts_v1_SynthesizeSpeechRequest,
        __Marshaller_tinkoff_cloud_tts_v1_StreamingSynthesizeSpeechResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Tinkoff.Cloud.Tts.V1.TtsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TextToSpeech</summary>
    [grpc::BindServiceMethod(typeof(TextToSpeech), "BindService")]
    public abstract partial class TextToSpeechBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses> ListVoices(global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse> Synthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task StreamingSynthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::IServerStreamWriter<global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TextToSpeech</summary>
    public partial class TextToSpeechClient : grpc::ClientBase<TextToSpeechClient>
    {
      /// <summary>Creates a new client for TextToSpeech</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TextToSpeechClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TextToSpeech that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TextToSpeechClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TextToSpeechClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TextToSpeechClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses ListVoices(global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListVoices(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses ListVoices(global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListVoices, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses> ListVoicesAsync(global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListVoicesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses> ListVoicesAsync(global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListVoices, null, options, request);
      }
      public virtual global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse Synthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Synthesize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse Synthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Synthesize, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse> SynthesizeAsync(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SynthesizeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse> SynthesizeAsync(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Synthesize, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse> StreamingSynthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamingSynthesize(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse> StreamingSynthesize(global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamingSynthesize, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TextToSpeechClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TextToSpeechClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TextToSpeechBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListVoices, serviceImpl.ListVoices)
          .AddMethod(__Method_Synthesize, serviceImpl.Synthesize)
          .AddMethod(__Method_StreamingSynthesize, serviceImpl.StreamingSynthesize).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, TextToSpeechBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListVoices, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.Cloud.Tts.V1.ListVoicesRequest, global::Tinkoff.Cloud.Tts.V1.ListVoicesResponses>(serviceImpl.ListVoices));
      serviceBinder.AddMethod(__Method_Synthesize, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechResponse>(serviceImpl.Synthesize));
      serviceBinder.AddMethod(__Method_StreamingSynthesize, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Tinkoff.Cloud.Tts.V1.SynthesizeSpeechRequest, global::Tinkoff.Cloud.Tts.V1.StreamingSynthesizeSpeechResponse>(serviceImpl.StreamingSynthesize));
    }

  }
}
#endregion
